# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
  #- TERRAFORM_TFLINT  
  - TERRAFORM_TERRASCAN
  #- TERRAFORM_TERRAFORM_FMT

TERRAFORM_TERRASCAN_ARGUMENTS:
  - "-l"
  - "debug"
  #- "--non-recursive"

#TERRAFORM_TFLINT_PRE_COMMANDS:
#  - command: "git config --global url.\"https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com\".insteadOf https://github.com"
#  - command: "terraform init -backend=false"

#TERRAFORM_TFLINT_UNSECURED_ENV_VARIABLES:
#  - GITHUB_TOKEN # Can contain string only, not regex

LOG_LEVEL: DEBUG

