name: Lint


on:
  push:
    branches: [main]

concurrency:
  group: ${{github.ref}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  run-megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/terraform@v7.7.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



